# Generated by Django 5.2.6 on 2025-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
